#pragma config(Sensor, in1,    lineTracker1,   sensorLineFollower)
#pragma config(Motor,  port1,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           backLeft,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          frontRight,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Mecanum Drive - Basic
- This program allows you to remotely control a robot with mecanum wheels.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        frontRight          VEX Motor             Front Right motor
Motor Port 3        backRight           VEX Motor             Back Right motor
Motor Port 4        frontLeft           VEX Motor             Front Left motor
Motor Port 5        backLeft            VEX Motor             Back Left motor
----------------------------------------------------------------------------------------------------*/

task main()
{
	int threshold = 1800;	//light value + dark value / 2

	//Loop Forever
	while(1 == 1)
	{


		if(SensorValue(lineTracker1) > threshold)
		{
			motor[frontRight] = 0;
			motor[backRight] = 0;
			motor[frontLeft] = 0;
			motor[backLeft] = 0;
			wait1Msec(1000);
		}
		else
		{

			//Remote Control Commands
			motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];// dont modify
			motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
			motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
			motor[backLeft] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
		}

		/*
		if you dont know how to read
		{
	break;
	}
	else
	{
die
}
		*/
	}

}
