#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Motor,  port1,           frontLeftMotor, tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           rearLeftMotor, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          frontRightMotor, tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int speed;



int threshold1 = 505;

task main()
{
	int  X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

	bool done = false;
	while (!done)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		//Remote Control Commands
		motor[frontRightMotor] = Y1 - X2 - X1;
		motor[rearRightMotor] =  Y1 - X2 + X1;
		motor[frontLeftMotor] = Y1 + X2 + X1;
		motor[rearLeftMotor] =  Y1 + X2 - X1;


	//**************************************
	// Light Follower
	/*The Line Tracking Sensor is an analog sensor, and
	it returns values in the range of 0 to 4095. Darker
	objects reflect less light, and are indicated by
	higher numbers. Lighter objects reflect more light,
	and are indicated by lower numbers.
	*/
	//**************************************
	// sensor sees dark:

	while (vexRT[Btn5U] == 1)
	{
		// SENSOR SEES DARK
		if(SensorValue(lineFollower) < threshold1)
		{
			motor[frontLeftMotor]  = 60;
			motor[rearLeftMotor] = 60;
			motor[frontRightMotor] = 60;
			motor[rearRightMotor] = 60;
		}
		// SENSOR SEES LIGHT
		else
		{
			motor[frontLeftMotor]  = 0;
			motor[rearLeftMotor] = 0;
			motor[frontRightMotor] = 0;
			motor[rearRightMotor] = 0;
		}
	}

	motor[frontLeftMotor]  = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;

}
}
