#pragma config(Motor,  port1,           rollerMotor,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[rollerMotor] = 127;
	}

}
